defaultContentLanguage: en
languages:
  en:
    contentDir: "content/en"
    languageCode: "en-US"
    languageName: "English"
    title: "Project Documentation"
    weight: 1
  de:
    contentDir: "content/de"
    languageCode: "de-DE"
    languageName: "Deutsch"
    title: "Projekt Dokumentation"
    weight: 2
