# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Korean language
ko:
  languageCode: ko
  contentDir: content/ko
  title: 한국어 웹사이트 제목
  params:
    description: 한국어 사이트 설명...
  menu:
    main:
      - name: 홈
        url: /
        weight: 1
      - name: 소개
        url: /about/
        weight: 2
      - name: 경력
        url: /experience/
        weight: 3
      - name: 정보
        url: post
        weight: 4
      - name: 문의
        url: /contact/
        weight: 5