# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/about.md
    weight: 20
  - name: Experience
    url: about/experience.md
    weight: 30
  - name: Field
    url: about/accomplishments.md
    weight: 30
  - name: Contact
    url: about/contact.md
    weight: 50