main:
  - name: Home
    url: /
    weight: 100
  - name: About
    url: about/
    weight: 200
  - name: Experience
    url: experience/
    weight: 300

  - name: Inform
    url: post
    weight: 400
  - parent: Inform
    name: Notifications
    url: notification
    weight: 410
  - parent: Inform
    name: News
    url: post
    weight: 420

  - name: Contact
    url: contact/
    weight: 500
