main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 20
  - name: Experience
    url: experience/
    weight: 30

  - name: Contact
    url: contact/
    weight: 40

  - name: Inform
    url: post
    weight: 600
  - parent: Inform
    name: Notifications
    url: notification
    weight: 610
  - parent: Inform
    name: News
    url: post
    weight: 620