widgets:
  - name: Home
    path: /
    weight: 10
  - name: About
    path: about/
    weight: 20
  - name: Experience
    path: experience/
    weight: 30

  - name: Contact
    path: contact/
    weight: 50
