widgets:
  - name: home
    path: /
    title: 'Home'
    weight: 10
  - name: about
    path: /about/
    title: 'About'
    weight: 20
  - name: experience
    path: /experience/
    title: 'Experience'
    weight: 30
  - name: field
    path: /field/
    title: 'Field'
    weight: 40
  - name: contact
    path: /contact/
    title: 'Contact'
    weight: 50
